version: '3.8'

volumes:
  onlinecart:

services:

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=pgadmin
    volumes:
      - "onlinecart:/var/lib/postgresql/data"

  redis:
    image: redis:5.0.9-alpine

  application:
    build: ./
#    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/products
      - SPRING_PROFILES_ACTIVE=dev
      - IMAGES_PATH=/appdata/images
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

    image: onlinecart
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - redis

