//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.29 at 10:34:14 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.polyan.ru/api/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.polyan.onlinecart.ws.soap.products;
